name: 測試構建 Client

on:
  push:
    branches:
      - dev
    path:
      - client

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0

      - name: 安裝 Package
        working-directory: ./client
        run: yarn

      - name: 構建 Client
        working-directory: ./client
        run: yarn build
