name: build client

on:
  push:
    branches:
      - dev
    path:
      - client

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
        - name: yarn build
          run: |
            yarn
            yarn build
          working-directory: ./client
