name: build client

on:
  push:
    branches:
      - dev
    path:
      - client

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
      - name: Install Package
        working-directory: ./client
        run: yarn
      - name: Build Client
        working-directory: ./client
        run: yarn build